version: '3'

services:
  webserver:
    image: nginx:1.21.6-alpine
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    - ./anatole/exampleSite/public:/usr/share/nginx/html:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot